#!/bin/bash

echo "Fetching ibc-go and SDK versions"

ADDRESSES=./addresses.json
OUTPUT=./versions.json

if [ -s $OUTPUT ]; then
        rm -f $OUTPUT
        touch $OUTPUT
else
        touch $OUTPUT
fi

jq -r '.[] .grpc' <$ADDRESSES | while read -r ADDR; do

echo $ADDR

HTTPS=443
HTTPS1=2083

HTTP=9090

if [[ "$ADDR" == *"$HTTP" ]]; then
NODE_INFO=$(grpcurl -plaintext $ADDR cosmos.base.tendermint.v1beta1.Service.GetNodeInfo) 
fi

if [[ "$ADDR" == *"$HTTPS" ]]; then
NODE_INFO=$(grpcurl $ADDR cosmos.base.tendermint.v1beta1.Service.GetNodeInfo) 
fi

if [[ "$ADDR" == *"$HTTPS1" ]]; then
NODE_INFO=$(grpcurl $ADDR cosmos.base.tendermint.v1beta1.Service.GetNodeInfo) 
fi

NETWORK_NAME=$(jq .defaultNodeInfo.network <<<"$NODE_INFO")
SDK_VERSION=$(jq .applicationVersion.cosmosSdkVersion <<<"$NODE_INFO")
IBCGO_VERSION=$(grep ibc-go -A 1 <<<"$NODE_INFO")
TENDERMINT_VERSION=$(jq .defaultNodeInfo.version <<<"$NODE_INFO")

echo {'"NETWORK_NAME"': "$NETWORK_NAME", '"SDK_VERSION"': "$SDK_VERSION", '"IBCGO_VERSION"': "{$IBCGO_VERSION}", '"TENDERMINT_VERSION"': "$TENDERMINT_VERSION"} >> $OUTPUT 

done
